# Generated by Django 5.2.13 on 2026-04-28 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NWFPGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "dzongkhag",
                    models.CharField(
                        choices=[
                            ("bumthang", "Bumthang"),
                            ("chhukha", "Chhukha"),
                            ("dagana", "Dagana"),
                            ("gasa", "Gasa"),
                            ("haa", "Haa"),
                            ("lhuentse", "Lhuentse"),
                            ("mongar", "Mongar"),
                            ("paro", "Paro"),
                            ("pemagatshel", "Pemagatshel"),
                            ("punakha", "Punakha"),
                            ("samdrup_jongkhar", "Samdrup Jongkhar"),
                            ("samtse", "Samtse"),
                            ("sarpang", "Sarpang"),
                            ("thimphu", "Thimphu"),
                            ("trashigang", "Trashigang"),
                            ("trashi_yangtse", "Trashi Yangtse"),
                            ("trongsa", "Trongsa"),
                            ("tsirang", "Tsirang"),
                            ("wangdue", "Wangdue Phodrang"),
                            ("zhemgang", "Zhemgang"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("gewog", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("dissolved", "Dissolved"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("headquarters_lat", models.FloatField(blank=True, null=True)),
                ("headquarters_lon", models.FloatField(blank=True, null=True)),
                ("total_members", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dissolved_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NWFP Group",
                "verbose_name_plural": "NWFP Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("dissolved", "Dissolved"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("dissolved", "Dissolved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="groups.nwfpgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Status History",
                "verbose_name_plural": "Group Status Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chairperson", "Chairperson"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="groups.nwfpgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Member",
                "verbose_name_plural": "Group Members",
                "ordering": ["role", "user__full_name"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
