# Generated by Django 5.2.13 on 2026-04-28 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("public", "Public Customer"),
                            ("seller", "Seller"),
                            ("officer", "Dzongkhag Officer"),
                            ("admin", "National Admin"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "dzongkhag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bumthang", "Bumthang"),
                            ("chhukha", "Chhukha"),
                            ("dagana", "Dagana"),
                            ("gasa", "Gasa"),
                            ("haa", "Haa"),
                            ("lhuentse", "Lhuentse"),
                            ("mongar", "Mongar"),
                            ("paro", "Paro"),
                            ("pemagatshel", "Pemagatshel"),
                            ("punakha", "Punakha"),
                            ("samdrup_jongkhar", "Samdrup Jongkhar"),
                            ("samtse", "Samtse"),
                            ("sarpang", "Sarpang"),
                            ("thimphu", "Thimphu"),
                            ("trashigang", "Trashigang"),
                            ("trashi_yangtse", "Trashi Yangtse"),
                            ("trongsa", "Trongsa"),
                            ("tsirang", "Tsirang"),
                            ("wangdue", "Wangdue Phodrang"),
                            ("zhemgang", "Zhemgang"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "dzongkhag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bumthang", "Bumthang"),
                            ("chhukha", "Chhukha"),
                            ("dagana", "Dagana"),
                            ("gasa", "Gasa"),
                            ("haa", "Haa"),
                            ("lhuentse", "Lhuentse"),
                            ("mongar", "Mongar"),
                            ("paro", "Paro"),
                            ("pemagatshel", "Pemagatshel"),
                            ("punakha", "Punakha"),
                            ("samdrup_jongkhar", "Samdrup Jongkhar"),
                            ("samtse", "Samtse"),
                            ("sarpang", "Sarpang"),
                            ("thimphu", "Thimphu"),
                            ("trashigang", "Trashigang"),
                            ("trashi_yangtse", "Trashi Yangtse"),
                            ("trongsa", "Trongsa"),
                            ("tsirang", "Tsirang"),
                            ("wangdue", "Wangdue Phodrang"),
                            ("zhemgang", "Zhemgang"),
                        ],
                        max_length=30,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
            },
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Profile",
                "verbose_name_plural": "Seller Profiles",
            },
        ),
    ]
