# Generated by Django 5.2.13 on 2026-04-28 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HarvestBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("species", models.CharField(db_index=True, max_length=200)),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
                ("harvest_date", models.DateField()),
                (
                    "quantity_harvested",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity_unit", models.CharField(max_length=20)),
                ("site_name", models.CharField(blank=True, max_length=200)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("elevation_m", models.FloatField(blank=True, null=True)),
                ("collector_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("officer_verified", models.BooleanField(default=False)),
                ("uploaded_via_csv", models.BooleanField(default=False)),
                ("source_file", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_batches",
                        to="groups.nwfpgroup",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_harvests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Harvest Batch",
                "verbose_name_plural": "Harvest Batches",
                "ordering": ["-harvest_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "quantity_available",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("harvest_location", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("expired", "Expired"),
                            ("reserved", "Reserved"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Batch",
                "verbose_name_plural": "Inventory Batches",
                "ordering": ["-created_at"],
            },
        ),
    ]
